version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "oa-configurator"
      - dependency-name: "orm-loader"
