blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/orgs/AustralianCancerDataNetwork/discussions
    about: Questions and general discussion about the CAVA stack.
