name: "🚀 Feature Request"
description: Propose a new feature or enhancement.
type: "Feature"
body:
  - type: checkboxes
    attributes:
      label: Pre-flight
      options:
        - label: I searched existing issues and this has not been requested before.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What are you trying to do that you currently cannot?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered and why you ruled them out.
