volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data

networks:
  cava-network:
    name: cava-network
    driver: bridge

services:
  pgadmin:
    profiles: [ "pgadmin"]
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - cava-network
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.c
      PGADMIN_DEFAULT_PASSWORD: pwd
      SCRIPT_NAME: /pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
  python:
    image: omop-alchemy-python:local
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
      args:
        INSTALL_DEV: "true"
    restart: unless-stopped
    networks:
      - cava-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENGINE_CDM: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ..:/workspace:rw
    command: tail -f /dev/null
  postgres:
    image: postgres:18
    networks:
      - cava-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/home/data:rw
      - postgres-data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - max_wal_size=20GB
      - -c
      - checkpoint_timeout=30min
      - -c
      - wal_compression=on
      - -c
      - shared_buffers=6GB
      - -c
      - work_mem=256MB
      - -c
      - maintenance_work_mem=2GB
      - -c
      - effective_cache_size=16GB
  cava-jupyter-notebook:
    profiles: [ "jupyter"]
    image: omop-alchemy-jupyter:local
    build:
      context: ..
      dockerfile: docker/jupyter/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cava-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENGINE_CDM: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JUPYTERHUB_SERVICE_PREFIX: /jupyter/
      JUPYTERHUB_BASE_URL: ${HTTP_TYPE}://${HOST}
    env_file:
      - .env
    volumes:
      - ..:/home/jovyan/work:rw
    command:
      - jupyter-lab
      - --ip=*
      - --NotebookApp.token=
      - --NotebookApp.password=
      - --NotebookApp.base_url=/jupyter
    ports:
      - "8888:8888"
    mem_limit: 12g
    shm_size: 4g
