name: Release Update
on:
  pull_request:
    types: [closed]
    branches: [main]
permissions:
  contents: write
jobs:
  draft:
    if: github.event.pull_request.merged == true
    uses: AustralianCancerDataNetwork/cava-devops/.github/workflows/release-drafter.yml@main
    secrets: inherit
